services:
  redis:
    image: "redis:7-alpine"
    ports:
      - "63790:6379"

  mysql-dev:
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: secure_2fa_development
    ports:
      - "33060:3306"

