default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  host: <%= ENV['MYSQL_HOST'] %>
  port: <%= ENV['MYSQL_PORT'] %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>

development:
  <<: *default
  database: secure_2fa_development

test:
  <<: *default
  database: secure_2fa_test

production:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  url: <%= ENV["DATABASE_URL"] %>
