service: secure_2fa
image: techwizardro/secure_2fa

ssh:
  user: root
  keys:
    - ~/.ssh/helpliviu

servers:
  web:
    hosts:
      - 91.99.166.72

proxy:
  host: secure-2fa.com

registry:
  username:
    - DOCKER_USER
  password:
    - DOCKER_PASSWORD

accessories:
  mysql:
    image: mysql:8.0
    host: 91.99.166.72
    port: 3306
    env:
      secret:
        - MYSQL_ROOT_PASSWORD
        - SECURE_2FA_DATABASE_PASSWORD
      clear:
        MYSQL_DATABASE: secure_2fa_production
        MYSQL_USER: secure_2fa
        MYSQL_PASSWORD: ${SECURE_2FA_DATABASE_PASSWORD}
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    cmd: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --bind-address=0.0.0.0
    files:
      - config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

env:
  secret:
    - RAILS_MASTER_KEY
    - MYSQL_ROOT_PASSWORD
    - SECURE_2FA_DATABASE_PASSWORD
    - DATABASE_URL
    - DATABASE_CACHE_URL
    - DATABASE_QUEUE_URL
    - DATABASE_CABLE_URL

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "secure_2fa_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
