service: secure_2fa
image: liviu/secure_2fa

ssh:
  user: root
  keys:
    - ~/.ssh/helpliviu

servers:
  web:
    hosts:
      - 91.99.166.72

proxy:
  host: secure-2fa.com

registry:
  username:
    - DOCKER_USER
  password:
    - DOCKER_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "secure_2fa_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
